<?php
 return array (
  'resize' => true,
  'relative_urls' => false,
  'branding' => false,
  'menubar' => 
  array (
    'edit' => true,
    'insert' => true,
    'view' => true,
    'format' => true,
    'table' => false,
    'tools' => false,
  ),
  'toolbar' => 'undo redo | formatselect | bold italic strikethrough underline | link unlink | alignleft aligncenter alignright | numlist bullist | removeformat | code fullscreen | mpgetimage',
  'plugins' => 
  array (
    'link' => true,
    'anchor' => false,
    'image' => false,
    'lists' => true,
    'preview' => true,
    'hr' => true,
    'code' => true,
    'fullscreen' => true,
    'media' => false,
    'cpmediapath' => false,
    'cpassetpath' => false,
    'table' => false,
    'contextmenu' => true,
    'paste' => true,
    'wordcount' => false,
    'visualblocks' => false,
    'visualchars' => false,
    'tabfocus' => false,
    'noneditable' => false,
    'insertdatetime' => false,
    'codesample' => false,
    'advlist' => false,
    'textcolor' => false,
    'pagebreak' => false,
    'imagetools' => false,
    'emoticons' => false,
    'colorpicker' => false,
    'charmap' => false,
    'autoresize' => false,
    'directionality' => false,
    'cpcollectionlink' => false,
    'toc' => false,
    'searchreplace' => false,
    'pageurl' => false,
    'cpvideolink' => false,
    'mpgetimage' => true,
  ),
  'height' => '250',
  '_id' => 'Advanced5cf7812f344cd',
  'name' => 'Advanced',
  '_created' => 1559724335,
  '_modified' => 1576328927,
  'absolute_urls' => false,
  'blocks' => 
  array (
    'p' => true,
    'h1' => true,
    'h2' => true,
    'h3' => true,
    'h4' => true,
    'h5' => true,
    'h6' => true,
    'pre' => true,
  ),
);
